# Generated by Django 4.2.5 on 2023-09-11 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_event_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(50, 'ENDED'), (40, 'ENDING'), (30, 'JOINING'), (20, 'STARTED'), (10, 'CONFIRMED')], default=10),
        ),
    ]
