# Generated by Django 4.2.5 on 2023-09-13 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_event_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.CharField(default='test', max_length=1000),
            preserve_default=False,
        ),
    ]
